# -*- coding: utf-8 -*-
"""Project - 106

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pq85kUGqZc87rbimNR1dJSbQZU5h4BBp
"""

import csv
import numpy as np
import plotly.express as px

std_m = []
dp = []

def getDataSource(data_path):

  with open(data_path) as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
      std_m.append(float(row["Marks In Percentage"]))
      dp.append(float(row["Days Present"]))

  return {"x":std_m,"y":dp}

def findCorrelation(datasource):
  correlation = np.corrcoef(datasource["x"],datasource["y"])

  print("correlation student marks and present days is ",round(correlation[0,1]))

def plotFigure(data_path):
  fig = px.scatter(x = std_m,y = dp)
  fig.show()

def setup():
  data_path = "/content/Student Marks vs Days Present.csv"
  datasource = getDataSource(data_path)
  findCorrelation(datasource)
  plotFigure(data_path)

setup()

import csv
import numpy as np
import plotly.express as px

std_m = []
dp = []

def getDataSource(data_path):

  with open(data_path) as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
      std_m.append(float(row["Coffee in ml"]))
      dp.append(float(row["sleep in hours"]))

  return {"x":std_m,"y":dp}

def findCorrelation(datasource):
  correlation = np.corrcoef(datasource["x"],datasource["y"])

  print("correlation between cups of coffee and hours of sleep is ",round(correlation[0,1]))

def plotFigure(data_path):
  fig = px.scatter(x = std_m,y = dp)
  fig.show()

def setup():
  data_path = "/content/cups of coffee vs hours of sleep.csv"
  datasource = getDataSource(data_path)
  findCorrelation(datasource)
  plotFigure(data_path)

setup()